# Generated by Django 5.2.12 on 2026-03-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0002_debit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('health', 'Healthcare'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('food', 'Food & Dining'), ('travel', 'Travel'), ('salary', 'Salary'), ('investment', 'Investment')], max_length=100),
        ),
    ]
